spring:
 application:
  name: gateway-service
 config:
  import: "optional:configserver:"
 cloud:
  config:
   discovery:
    enable: true
    serviceId: config-service
  gateway:
   routes:
    - id: checkout-service
      uri: lb://checkout-service
      predicates:
        - Path=/checkout
      filters:
        - AddRequestHeader=X-Request-from, gateway
    - id: products-service
      uri: lb://products-service
      predicates:
        - Path=/products
server:
 port: 8085