spring:
 application:
  name: gateway-service
 config:
  import: "optional:configserver:"
 cloud:
  config:
   discovery:
    enable: true
    serviceId: config-service
  gateway:
   routes:
    - id: checkout-service
      uri: http://localhost:8084
      predicates:
       - Path=/checkout
server:
 port: 8084